// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb_M3v29lGxD7fwjI60BCd7lSRA6ViHmU',
    appId: '1:501413303083:web:2e855b7376784c8383ab6e',
    messagingSenderId: '501413303083',
    projectId: 'firstsocial-18516',
    authDomain: 'firstsocial-18516.firebaseapp.com',
    storageBucket: 'firstsocial-18516.appspot.com',
    measurementId: 'G-HN81MRYDHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVOJmvRAqJ3w3pjKyNUPvPmpHRPju_iWQ',
    appId: '1:501413303083:android:979d36bff2304f9983ab6e',
    messagingSenderId: '501413303083',
    projectId: 'firstsocial-18516',
    storageBucket: 'firstsocial-18516.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpVPmZ_xsY5CWmUZmkA0F3OU-fpIKMqNI',
    appId: '1:501413303083:ios:1d4f688e4a9907be83ab6e',
    messagingSenderId: '501413303083',
    projectId: 'firstsocial-18516',
    storageBucket: 'firstsocial-18516.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpVPmZ_xsY5CWmUZmkA0F3OU-fpIKMqNI',
    appId: '1:501413303083:ios:921dbc7ac1488e2f83ab6e',
    messagingSenderId: '501413303083',
    projectId: 'firstsocial-18516',
    storageBucket: 'firstsocial-18516.appspot.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
